### PR TITLE
update verify to use new auth0 actions

### PR DESCRIPTION
**Pull request by jmckenna-settlor**
i updated the code slightly to use the new auth0 actions since hooks will be deprecated soon.

### CODE REVIEW

**Comment by mingchaoma** [comment]
Hi John,

Thanks for the head-up, yes, I am aware hooks will be deprecated soon, but didn't get around to update my code. Thanks for the PR.  Before I merge the PR, I will have to update my blog post, probably sometime in Sep.

Do give me a nudge if nothing happens after Sep.

Thanks,

Mingchao

**Comment by jmckenna-settlor** [comment]
we found an edge case where the phone number could be entered with spaces and it made twilio sad. so i fixed that.

**Comment by jmckenna-settlor** [comment]
bump it's september.

**Comment by mingchaoma** [comment]
many thanks. I just managed to update my blog post.

**Pull request merged**
